FROM openjdk:11
EXPOSE 8001
ADD target/communication-history-service-0.0.1-SNAPSHOT.jar communication-history-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/communication-history-service-0.0.1-SNAPSHOT.jar"]