# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

env: 
  PROJECT_NAME: communication-history-service
on:
  push:
    branches: [ "main" ]
    paths:
      - ${{ env.PROJECT_NAME }}/src/**
      - .github/workflows/${{ env.PROJECT_NAME }}-ci.yaml
  pull_request:
    branches: [ "main" ]

name: $PROJECT_NAME} CI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      working-directory: ./${{ env.PROJECT_NAME }}
      run: mvn clean package -DskipTests
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.PROJECT_NAME }}-artifact
        path: ${{ env.PROJECT_NAME }}/target
